config_version: any(int(), str())

general:
  device_codename: str(required=False)
  os_name: str()
  os_version: num()
  template: str(required=False)

repositories: list(include('repository'))

apps: >
  list(
    str(),
    include('app_fdroid_latest'),
    include('app_fdroid_version'),
    include('app_fdroid_versioncode'),
    include('app_direct_download'),
  )

defaults:
  repository: str()
  app_type: str(required=False)
  hash_type: str(required=False)

---

repository:
  id: str()
  name: str()
  url: str()
  fallback: str(required=False)

app_fdroid_latest:
  id: str()
  repository: str(required=False)
  app_type: enum('system', 'privileged', 'user', required=False)

app_fdroid_version:
  id: str()
  version: str()
  hash: str()
  hash_type: str(required=False)
  repository: str(required=False)
  app_type: enum('system', 'privileged', 'user', required=False)

app_fdroid_versioncode:
  id: str()
  versioncode: int()
  hash: str()
  hash_type: str(required=False)
  repository: str(required=False)
  app_type: enum('system', 'privileged', 'user', required=False)

app_direct_download:
  id: str()
  name: str()
  hash: str()
  hash_type: str(required=False)
  url: str()
  app_type: enum('system', 'privileged', 'user', 'supersu', required=False)
